networks:
  vpc:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  app-blue:
    image: rayoh95/anpetna:latest
    container_name: app-blue
    hostname: app-blue
    expose: ["8080"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://192.168.0.181:3306/anpetnadb
      SPRING_DATASOURCE_USERNAME: anpetnaitem
      SPRING_DATASOURCE_PASSWORD: anpetna220
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks: [vpc]

  app-green:
    image: rayoh95/anpetna:latest
    container_name: app-green
    hostname: app-green
    expose: ["8080"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://192.168.0.181:3306/anpetnadb
      SPRING_DATASOURCE_USERNAME: anpetnaitem
      SPRING_DATASOURCE_PASSWORD: anpetna220
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks: [vpc]

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    hostname: api-gateway
    ports: ["80:80"]
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
    depends_on:
      - app-blue
      - app-green
    networks: [vpc]
