package com.anpetna.notification.common.constant;

public enum NotificationType {
    COMMENT, POST_LIKE, KEYWORD_MATCH, PAYMENT_DONE, PAYMENT_FAIL, COMMENT_LIKE, STOCK_LOW, RESERVATION_HOSPITAL, RESERVATION_HOTEL,
    RESERVATION_HOSPITAL_CANCELED, RESERVATION_HOTEL_CANCELED, RESERVATION_HOSPITAL_NOSHOW, RESERVATION_HOTEL_NOSHOW,
    RESERVATION_HOSPITAL_CONFIRM, RESERVATION_HOTEL_CONFIRM, RESERVATION_REMINDER_24H, RESERVATION_REMINDER_3H

}
